#include "stdafx.h"

/*
A string "aBIY" is said to be a well-ordered word as each of the letters 
are in sequential manner regardless of case. So, "AbLe" is not a well-ordered word.
You are a anti-hacker. you have a number of character sequences. 
Your task is to generate all possible well-ordered word that can be generated by those numbers of given character sequences.
*/

#include <iostream>
#include <algorithm>
#include <iomanip>
#include <string>
#include <vector>
#include <unordered_set>
#include <assert.h>

using namespace std;

void Epic2()
{
}

#if !defined(_MSC_VER)
int main()
{
	Epic2();
	return 0;
}
#endif
